{"name": "Неверные логин или пароль: 404 и сообщение об ошибке", "status": "passed", "steps": [{"name": "Отправляем запрос логина с неверным паролем", "status": "passed", "attachments": [{"name": "response.json", "source": "fe25a0dd-3711-43a3-8af4-7c42b59a4ef4-attachment.json", "type": "application/json"}], "start": 1760894753957, "stop": 1760894754171}, {"name": "Проверяем код ответа и текст ошибки", "status": "passed", "start": 1760894754171, "stop": 1760894754171}], "start": 1760894753957, "stop": 1760894754172, "uuid": "beb5d2d3-f1eb-4504-ae75-a83ab3674d1d", "historyId": "ff16a5c77cf67bd60dd827a37ba41b1a", "testCaseId": "ff16a5c77cf67bd60dd827a37ba41b1a", "fullName": "tests.test_courier_login.TestCourierLogin#test_login_wrong_credentials_returns_error", "labels": [{"name": "feature", "value": "Courier"}, {"name": "epic", "value": "Scooter API"}, {"name": "story", "value": "Login courier"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "m00office0012.local"}, {"name": "thread", "value": "83094-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}], "titlePath": ["tests", "test_courier_login.py", "TestCourierLogin"]}